# Generated by Django 2.1.5 on 2019-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=250)),
                ('Sphoto', models.FileField(upload_to='')),
                ('Fname', models.CharField(max_length=250)),
                ('Fphoto', models.FileField(upload_to='')),
                ('Mname', models.CharField(max_length=250)),
                ('Mphoto', models.FileField(upload_to='')),
                ('School', models.CharField(max_length=500)),
                ('Grade', models.CharField(max_length=100)),
                ('PYmarks', models.FileField(upload_to='')),
                ('PPYmarks', models.FileField(upload_to='')),
                ('Marks', models.CharField(max_length=100)),
                ('Incomecert', models.FileField(upload_to='')),
                ('Foccup', models.CharField(max_length=100)),
                ('Moccup', models.CharField(max_length=100)),
                ('Sfee', models.CharField(max_length=100)),
                ('Scholar', models.CharField(max_length=100)),
            ],
        ),
    ]
